spring:
    datasource:
        url: jdbc:mysql://localhost:3306/device
        username: root
        password: root
        driver-class-name: com.mysql.jdbc.Driver
    # Redis 相关配置
    redis:
        database: 5
        host: 127.0.0.1
        password:
        port: 6379
        timeout: 1000ms
        lettuce:
            pool:   # 连接池中的最大空闲连接，默认值也是8。
                max-idle: 500
                min-idle: 50
                max-active: 2000
                max-wait: 1000ms



#阿里云短信相关配置
aliYun:
  SMS:
      accessKeyId: LTAI8Zwfik2OicUs
      accessKeySecret: nldeasjfaqQl2i3Zb7Kg7VqfHGuOhF
      sign: 阿里云短信测试专用


