server:
  port: 8083

spring:
  profiles:
    active: test
  application:
    name: sys-user-provider

eureka:
  client:
    service-url:
     defaultZone: http://10.86.2.203:8081/eureka/

mybatis:
  typeAliasesPackage: com.atom.entity
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    root: INFO