server:
  port: 8081


eureka:
  instance:
    hostname: localhost
    lease-renewal-interval-in-second: 5
    lease-expiration-duration-in-second: 10
  client:
    service-url:
     defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
    register-with-eureka: false
    fetch-registry: false

