server:
  port: 8082

spring:
  application:
    name: user-provider
  datasource:
      url: jdbc:mysql://localhost:3306/device
      username: root
      password: root
      driver-class-name: com.mysql.jdbc.Driver

eureka:
  client:
    service-url:
     defaultZone: http://10.86.2.203:8081/eureka/

mybatis:
  typeAliasesPackage: com.atom.entity
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    root: INFO