server:
  port: 8088

spring:
  profiles:
    active: test
  application:
    name: dalgen-start

eureka:
  client:
    service-url:
     defaultZone: http://10.86.2.203:8081/eureka/

mybatis:
  typeAliasesPackage: com.atom.sys.user.entity
  mapperLocations: classpath:mapper/*.xml

logging:
  level:
    root: info